package violations

type ViolationType string

const (
	REQUIRED_ENTITIES_TYPE ViolationType = "REQUIRED_ENTITIES"

	// Namespace
	NO_OWNER_ANNOTATION_TYPE            ViolationType = "NO_OWNER_ANNOTATION"
	REQUIRED_NAMESPACES_TYPE            ViolationType = "REQUIRED_NAMESPACES"
	REQUIRED_NAMESPACE_ANNOTATIONS_TYPE ViolationType = "REQUIRED_NAMESPACE_ANNOTATIONS"
	REQUIRED_NAMESPACE_LABELS_TYPE      ViolationType = "REQUIRED_NAMESPACE_LABELS"

	// Deployment
	SINGLE_REPLICA_TYPE                  ViolationType = "SINGLE_REPLICA"
	REQUIRED_DEPLOYMENTS_TYPE            ViolationType = "REQUIRED_DEPLOYMENTS"
	REQUIRED_DEPLOYMENT_ANNOTATIONS_TYPE ViolationType = "REQUIRED_DEPLOYMENT_ANNOTATIONS"
	REQUIRED_DEPLOYMENT_LABELS_TYPE      ViolationType = "REQUIRED_DEPLOYMENT_LABELS"

	// IMAGES
	IMAGE_REPO_TYPE ViolationType = "IMAGE_REPO"
	IMAGE_SIZE_TYPE ViolationType = "IMAGE_SIZE"

	// VOLUMES
	HOST_VOLUMES_TYPE ViolationType = "HOST_VOLUMES"

	// INGRESS
	INGRESS_HOST_INVALID_TYPE ViolationType = "INGRESS_HOST_INVALID"

	// CAPS
	PRIVILEGED_TYPE   ViolationType = "PRIVILEGED"
	CAPABILITIES_TYPE ViolationType = "CAPABILITIES"

	// PODS
	REQUIRED_PODS_TYPE            ViolationType = "REQUIRED_PODS"
	REQUIRED_POD_ANNOTATIONS_TYPE ViolationType = "REQUIRED_POD_ANNOTATIONS"
	REQUIRED_POD_LABELS_TYPE      ViolationType = "REQUIRED_POD_LABELS"

	// DAEMONSETS
	REQUIRED_DAEMONSETS_TYPE            ViolationType = "REQUIRED_DAEMONSETS"
	REQUIRED_DAEMONSET_ANNOTATIONS_TYPE ViolationType = "REQUIRED_DAEMONSET_ANNOTATIONS"
	REQUIRED_DAEMONSET_LABELS_TYPE      ViolationType = "REQUIRED_DAEMONSET_LABELS"
)
